title: <span class="together">Federal Cloud</span> <span class="together">Computing Strategy</span>

# GitHub information
# This is used for adding an edit this page link to the footer
github:
  organization: ombegov
  repository: cloud.cio.gov
  default_branch: gh-pages

# Configuration for setting the site width to 100%
# To enable, uncomment the following line
# site_width: wide

# Configuration for Google Analytics, add your UA code here:
google_analytics_ua: UA-33523145-1

# Configuration for DAP, add your agency ID here:
dap_agency: EOP

# Uncomment to enable AnchorJS functionality on docs layout.
# See https://github.com/bryanbraun/anchorjs for more information.
# anchor_js_targets: [h1, h2, h3, h4, h5, h6]

# To enable search, uncomment the search section
# You will need to setup a search account with search.gov
# https://search.usa.gov/signup
# Your search_site_handle value is from the search.gov settings page.

# search_site_handle: searchgov-site-handle

# Configuration for projects and team collections
# See https://jekyllrb.com/docs/collections/ for more information about collections.
# collections:
#   projects:
#     output: true
#   team:
#     output: true

# Set this to false once the policy is no longer a draft, to remove the "draft" banner.
draft: true

mail: ofcio@omb.eop.gov

styles:
  - '/assets/fontawesome/css/fontawesome-all.min.css'
  - '/assets/css/custom.css'

logo: <span class="logo-wrapper"><svg class="logo" role="img" aria-label="Image of a cloud shaped like a brain" xmlns="http://www.w3.org/2000/svg" width="83" height="62" viewBox="0 0 83.1 62.3"><style>.logo-stroke{fill:none;stroke-linejoin:round;stroke-width:2;stroke:#FFF;}.logo-fill{fill:#19A1D8;}</style><path d="M26.1 48.5c-1.6 0.6-3.2 0.9-5 0.9 -7.8 0-14.1-6.3-14.1-14.1 0-7.3 5.5-13.2 12.5-14v-0.1c0-9.4 7.6-17.1 17-17.1 5.1 0 9.6 2.2 12.7 5.7 1.5-0.6 3.1-1 4.9-1 7 0 12.6 5.7 12.6 12.7 0 0.1 0 0.2 0 0.4 5.8 2.3 9.8 7.9 9.8 14.5 0 8.6-7 15.6-15.6 15.6 -3.7 0-7-1.3-9.7-3.4 -2.8 3.8-7.4 6.3-12.5 6.3C33.5 55 28.9 52.4 26.1 48.5" class="logo-fill"/><path d="M26.1 48.5c-1.6 0.6-3.2 0.9-5 0.9 -7.8 0-14.1-6.3-14.1-14.1 0-7.3 5.5-13.2 12.5-14v-0.1c0-9.4 7.6-17.1 17-17.1 5.1 0 9.6 2.2 12.7 5.7 1.5-0.6 3.1-1 4.9-1 7 0 12.6 5.7 12.6 12.7 0 0.1 0 0.2 0 0.4 5.8 2.3 9.8 7.9 9.8 14.5 0 8.6-7 15.6-15.6 15.6 -3.7 0-7-1.3-9.7-3.4 -2.8 3.8-7.4 6.3-12.5 6.3C33.5 55 28.9 52.4 26.1 48.5z" class="logo-stroke"/><path d="M51 48.5c0.8 0.4-3.7-2.3-4.6-6.7" class="logo-stroke"/><path d="M69.8 36.1c0 0-6.5 0-8 7.3" class="logo-stroke"/><path d="M19.5 21.3c0 0 5.7-0.8 10 2.3" class="logo-stroke"/><path d="M47.1 17.8c0 0 3 4.5-2.6 8.6" class="logo-stroke"/><path d="M47.9 22.1c0 0 5.2-2.1 9.5 4.3" class="logo-stroke"/><path d="M26.1 48.5c0 0-4.5-2.1-4.2-7.8" class="logo-stroke"/><path d="M30 32.3c0 0-1.5 4 2.1 6.8 -0.2 3.2 2 5.1 5.6 5.5" class="logo-stroke"/></svg></span>
